### ISSUE TITLE
Application causes requirement of discrete graphics card on apple laptops with multiple cards.

### ISSUE THREAD

**Issue by ghost** [memoryio/memoryio-macosx#22]
OSX automatically switches to the discrete card when the camera is operated.

The problem here is that the discrete graphics card remains selected after the photo is taken, while the application is running.

![screen shot 2013-10-29 at 3 30 45 pm](https://f.cloud.github.com/assets/45108/1433050/c58fc1c0-40e9-11e3-8e9a-9568c66d6e1b.png)

**Comment by jacobrosenthal** [comment]
Be interesting to hear back on this now that were on the new avfoundation api
